waveform add -signals {tb.bl.axi_araddr}
waveform add -signals {tb.bl.axi_arready}
waveform add -signals {tb.bl.axi_awaddr}
waveform add -signals {tb.bl.axi_awready}
waveform add -signals {tb.bl.axi_bresp}
waveform add -signals {tb.bl.axi_bvalid}
waveform add -signals {tb.bl.axi_rdata}
waveform add -signals {tb.bl.axi_rresp}
waveform add -signals {tb.bl.axi_rvalid}
waveform add -signals {tb.bl.axi_wready}
waveform add -signals {tb.bl.b}
waveform add -signals {tb.bl.clk}
waveform add -signals {tb.bl.reg0}
waveform add -signals {tb.bl.reg_data_out}
waveform add -signals {tb.bl.s00_axi_aclk}
waveform add -signals {tb.bl.s00_axi_araddr}
waveform add -signals {tb.bl.s00_axi_aresetn}
waveform add -signals {tb.bl.s00_axi_arprot}
waveform add -signals {tb.bl.s00_axi_arready}
waveform add -signals {tb.bl.s00_axi_arvalid}
waveform add -signals {tb.bl.s00_axi_awaddr}
waveform add -signals {tb.bl.s00_axi_awprot}
waveform add -signals {tb.bl.s00_axi_awready}
waveform add -signals {tb.bl.s00_axi_awvalid}
waveform add -signals {tb.bl.s00_axi_bready}
waveform add -signals {tb.bl.s00_axi_bresp}
waveform add -signals {tb.bl.s00_axi_bvalid}
waveform add -signals {tb.bl.s00_axi_rdata}
waveform add -signals {tb.bl.s00_axi_rready}
waveform add -signals {tb.bl.s00_axi_rresp}
waveform add -signals {tb.bl.s00_axi_rvalid}
waveform add -signals {tb.bl.s00_axi_wdata}
waveform add -signals {tb.bl.s00_axi_wready}
waveform add -signals {tb.bl.s00_axi_wstrb}
waveform add -signals {tb.bl.s00_axi_wvalid}
waveform add -signals {tb.bl.slv_reg}
waveform add -signals {tb.bl.slv_reg_rden}
waveform add -signals {tb.bl.slv_reg_wren}
