waveform add -signals {tb.bl.axi_araddr[4:0]}
waveform add -signals {tb.bl.axi_arready}
waveform add -signals {tb.bl.axi_awaddr[4:0]}
waveform add -signals {tb.bl.axi_awready}
waveform add -signals {tb.bl.axi_bresp[1:0]}
waveform add -signals {tb.bl.axi_bvalid}
waveform add -signals {tb.bl.axi_rdata[31:0]}
waveform add -signals {tb.bl.axi_rresp[1:0]}
waveform add -signals {tb.bl.axi_rvalid}
waveform add -signals {tb.bl.axi_wready}
waveform add -signals {tb.bl.b}
waveform add -signals {tb.bl.clk}
waveform add -signals {tb.bl.reg0[31:0]}
waveform add -signals {tb.bl.reg_data_out[31:0]}
waveform add -signals {tb.bl.s00_axi_aclk}
waveform add -signals {tb.bl.s00_axi_araddr[4:0]}
waveform add -signals {tb.bl.s00_axi_aresetn}
waveform add -signals {tb.bl.s00_axi_arprot[2:0]}
waveform add -signals {tb.bl.s00_axi_arready}
waveform add -signals {tb.bl.s00_axi_arvalid}
waveform add -signals {tb.bl.s00_axi_awaddr[4:0]}
waveform add -signals {tb.bl.s00_axi_awprot[2:0]}
waveform add -signals {tb.bl.s00_axi_awready}
waveform add -signals {tb.bl.s00_axi_awvalid}
waveform add -signals {tb.bl.s00_axi_bready}
waveform add -signals {tb.bl.s00_axi_bresp[1:0]}
waveform add -signals {tb.bl.s00_axi_bvalid}
waveform add -signals {tb.bl.s00_axi_rdata[31:0]}
waveform add -signals {tb.bl.s00_axi_rready}
waveform add -signals {tb.bl.s00_axi_rresp[1:0]}
waveform add -signals {tb.bl.s00_axi_rvalid}
waveform add -signals {tb.bl.s00_axi_wdata[31:0]}
waveform add -signals {tb.bl.s00_axi_wready}
waveform add -signals {tb.bl.s00_axi_wstrb[3:0]}
waveform add -signals {tb.bl.s00_axi_wvalid}
waveform add -signals {tb.bl.slv_reg0[31:0]}
waveform add -signals {tb.bl.slv_reg1[31:0]}
waveform add -signals {tb.bl.slv_reg2[31:0]}
waveform add -signals {tb.bl.slv_reg_rden}
waveform add -signals {tb.bl.slv_reg_wren}
